# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sdxl_turbo_pb2 as proto_dot_sdxl__turbo__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/sdxl_turbo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDXLTurboServiceStub(object):
    """The SDXL-Turbo service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Img2Img = channel.unary_unary(
                '/sdxl_turbo.SDXLTurboService/Img2Img',
                request_serializer=proto_dot_sdxl__turbo__pb2.Img2ImgRequest.SerializeToString,
                response_deserializer=proto_dot_sdxl__turbo__pb2.Img2ImgResponse.FromString,
                _registered_method=True)
        self.Img2ImgBatch = channel.unary_unary(
                '/sdxl_turbo.SDXLTurboService/Img2ImgBatch',
                request_serializer=proto_dot_sdxl__turbo__pb2.Img2ImgBatchRequest.SerializeToString,
                response_deserializer=proto_dot_sdxl__turbo__pb2.Img2ImgBatchResponse.FromString,
                _registered_method=True)
        self.GetQueueStatus = channel.unary_unary(
                '/sdxl_turbo.SDXLTurboService/GetQueueStatus',
                request_serializer=proto_dot_sdxl__turbo__pb2.QueueStatusRequest.SerializeToString,
                response_deserializer=proto_dot_sdxl__turbo__pb2.QueueStatusResponse.FromString,
                _registered_method=True)


class SDXLTurboServiceServicer(object):
    """The SDXL-Turbo service definition
    """

    def Img2Img(self, request, context):
        """Single image generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Img2ImgBatch(self, request, context):
        """Batch image generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStatus(self, request, context):
        """Get queue status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDXLTurboServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Img2Img': grpc.unary_unary_rpc_method_handler(
                    servicer.Img2Img,
                    request_deserializer=proto_dot_sdxl__turbo__pb2.Img2ImgRequest.FromString,
                    response_serializer=proto_dot_sdxl__turbo__pb2.Img2ImgResponse.SerializeToString,
            ),
            'Img2ImgBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Img2ImgBatch,
                    request_deserializer=proto_dot_sdxl__turbo__pb2.Img2ImgBatchRequest.FromString,
                    response_serializer=proto_dot_sdxl__turbo__pb2.Img2ImgBatchResponse.SerializeToString,
            ),
            'GetQueueStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStatus,
                    request_deserializer=proto_dot_sdxl__turbo__pb2.QueueStatusRequest.FromString,
                    response_serializer=proto_dot_sdxl__turbo__pb2.QueueStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdxl_turbo.SDXLTurboService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdxl_turbo.SDXLTurboService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDXLTurboService(object):
    """The SDXL-Turbo service definition
    """

    @staticmethod
    def Img2Img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdxl_turbo.SDXLTurboService/Img2Img',
            proto_dot_sdxl__turbo__pb2.Img2ImgRequest.SerializeToString,
            proto_dot_sdxl__turbo__pb2.Img2ImgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Img2ImgBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdxl_turbo.SDXLTurboService/Img2ImgBatch',
            proto_dot_sdxl__turbo__pb2.Img2ImgBatchRequest.SerializeToString,
            proto_dot_sdxl__turbo__pb2.Img2ImgBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdxl_turbo.SDXLTurboService/GetQueueStatus',
            proto_dot_sdxl__turbo__pb2.QueueStatusRequest.SerializeToString,
            proto_dot_sdxl__turbo__pb2.QueueStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
